#ifndef _RULES_H
#define _RULES_H

// Combat
#define RULE_COMBAT_ATTACK_COST 7
#define RULE_COMBAT_REPAIR_COST 15
#define RULE_COMBAT_FLEE_COST 10

// Shop
#define RULE_SHOP_HEALTH_COST 20
#define RULE_SHOP_SCRAPS_COST 20
#define RULE_SHOP_LEAVE_COST 0
#define RULE_SHOP_HEALTH_BACK 20
#define RULE_SHOP_SCRAPS_BACK 15

#endif /* _RULES_H */
